
const beer = [
  { brewery: "Schlafly", Pumpkin: "Pumpkin Ale" },
  { brewery: "Schlafly", Marzen: "Oktoberfest" },
  { brewery: "Schlafly", SummerAle: "Summer Lager" },
  { brewery: "Schlafly", WinterLager: "ESB" },
  { brewery: "Schlafly", WinterLager: "Christmas Ale" },
  { brewery: "Schlafly", WinterLager: "Merry Berry Ale" },
  { brewery: "Schlafly", IrishStout: "Irish-Style Extra Stout" },
  { brewery: "Schlafly", CoffeeStout: "Coffee Stout" },
  { brewery: "Urban Chestnut", Pumpkin: "Count Orlok Black Pumpkin Ale" },
  { brewery: "Urban Chestnut", Marzen: "Oachkatzlschwoaf" },
  { brewery: "Urban Chestnut", SummerAle: "Solaris" },
  { brewery: "Urban Chestnut", SummerAle: "Big Shark Lemon Radler" },
  { brewery: "Urban Chestnut", SummerAle: "Big Shark Grapefruit Radler" },
  { brewery: "Urban Chestnut", WinterLager: "Horchata Kinsale" },
  { brewery: "Urban Chestnut", WinterLager: "Cherry Thrale's" },
  { brewery: "Urban Chestnut", IrishStout: "O'Florian's" },
  { brewery: "Urban Chestnut", CoffeeStout: "Kinsale" },
  { brewery: "4 Hands", Pumpkin: "Ill Repute" },
  { brewery: "4 Hands", SummerAle: "Dakine" },
  { brewery: "4 Hands", SummerAle: "On Cue" },
  { brewery: "4 Hands", SummerAle: "Contact High Juiced" },
  { brewery: "4 Hands", CoffeeStout: "Devil's Invention" },
  { brewery: "4 Hands", WinterLager: "Chocolate Milk Stout" },
  { brewery: "Civil Life", Marzen: "Oktoberfest" },
  { brewery: "Civil Life", SummerAle: "Vienna Lager" },
  { brewery: "Civil Life", IrishStout: "Extra Stout" },
  { brewery: "Modern", WinterLager: "Arkham's Finest" },
  { brewery: "Modern", WinterLager: "The Heeler" },
  { brewery: "Modern", IrishStout: "Clandestine" },
  { brewery: "Modern", Marzen: "Oktoberfest" },
  { brewery: "2nd Shift", Marzen: "Oktoberfest" },
  { brewery: "2nd Shift", SummerAle: "Kolsch" },
  { brewery: "2nd Shift", SummerAle: "Arancia E Ibisco" },
  { brewery: "2nd Shift", WinterLager: "Cat Spit Stout" },
  { brewery: "2nd Shift", WinterLager: "Liquid Spiritual Delight" },
  { brewery: "Square One", Pumpkin: "Spiced Pumpkin Ale" },
  { brewery: "Square One", IrishStout: "Irish Stout" },
  { brewery: "Square One", Marzen: "Oktoberfest" },
  { brewery: "Square One", SummerAle: "Summer Saison" },
  { brewery: "Square One", WinterLager: "Smoked Porter" }
]
