export default [
  { brewery: "Schlafly", Pumpkin: "Pumpkin Ale", Availability: true },
  { brewery: "Schlafly", Marzen: "Oktoberfest", Availability: true },
  { brewery: "Schlafly", SummerAle: "Summer Lager", Availability: false },
  { brewery: "Schlafly", WinterLager: "ESB", Availability: false },
  { brewery: "Schlafly", WinterLager: "Christmas Ale", Availability: false },
  { brewery: "Schlafly", WinterLager: "Merry Berry Ale", Availability: false },
  { brewery: "Schlafly", IrishStout: "Irish-Style Extra Stout", Availability: false },
  { brewery: "Schlafly", CoffeeStout: "Coffee Stout", Availability: true },
  { brewery: "Urban Chestnut", Pumpkin: "Count Orlok Black Pumpkin Ale", Availability: true },
  { brewery: "Urban Chestnut", Marzen: "Oachkatzlschwoaf", Availability: true },
  { brewery: "Urban Chestnut", SummerAle: "Solaris", Availability: false },
  { brewery: "Urban Chestnut", SummerAle: "Big Shark Lemon Radler", Availability: false },
  { brewery: "Urban Chestnut", SummerAle: "Big Shark Grapefruit Radler", Availability: false },
  { brewery: "Urban Chestnut", WinterLager: "Horchata Kinsale", Availability: false },
  { brewery: "Urban Chestnut", WinterLager: "Cherry Thrale's", Availability: false },
  { brewery: "Urban Chestnut", IrishStout: "O'Florian's", Availability: false },
  { brewery: "Urban Chestnut", CoffeeStout: "Kinsale", Availability: true },
  { brewery: "4 Hands", Pumpkin: "Ill Repute", Availability: true },
  { brewery: "4 Hands", SummerAle: "Dakine", Availability: false },
  { brewery: "4 Hands", SummerAle: "On Cue", Availability: false },
  { brewery: "4 Hands", SummerAle: "Contact High Juiced", Availability: false },
  { brewery: "4 Hands", CoffeeStout: "Devil's Invention", Availability: true },
  { brewery: "4 Hands", WinterLager: "Chocolate Milk Stout", Availability: true },
  { brewery: "Civil Life", Marzen: "Oktoberfest", Availability: true },
  { brewery: "Civil Life", SummerAle: "Vienna Lager", Availability: false },
  { brewery: "Civil Life", IrishStout: "Extra Stout", Availability: false },
  { brewery: "Modern", WinterLager: "Arkham's Finest", Availability: true },
  { brewery: "Modern", WinterLager: "The Heeler", Availability: true },
  { brewery: "Modern", IrishStout: "Clandestine", Availability: false },
  { brewery: "Modern", Marzen: "Oktoberfest", Availability: true },
  { brewery: "2nd Shift", Marzen: "Oktoberfest", Availability: true },
  { brewery: "2nd Shift", SummerAle: "Kolsch", Availability: false },
  { brewery: "2nd Shift", SummerAle: "Arancia E Ibisco", Availability: false },
  { brewery: "2nd Shift", WinterLager: "Cat Spit Stout", Availability: true },
  { brewery: "2nd Shift", WinterLager: "Liquid Spiritual Delight", Availability: true },
  { brewery: "Square One", Pumpkin: "Spiced Pumpkin Ale", Availability: true },
  { brewery: "Square One", IrishStout: "Irish Stout", Availability: false },
  { brewery: "Square One", Marzen: "Oktoberfest", Availability: true },
  { brewery: "Square One", SummerAle: "Summer Saison", Availability: false },
  { brewery: "Square One", WinterLager: "Smoked Porter", Availability: false }
];
